import React from "react";
import { Zap } from "lucide-react";

export function ReportProcessingStatus() {
  return (
    <div className="p-3 bg-green-900/20 border border-green-400/30 rounded-lg">
      <div className="flex items-center gap-2 text-green-400 text-sm">
        <Zap className="w-4 h-4 animate-pulse" />
        <span>Your report is being generated by AI. This may take several minutes...</span>
      </div>
    </div>
  );
} 